{
 "title": "Test Results Overall",
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "version",
    "query": "SHOW TAG VALUES WITH KEY = \"version\" "
   }
  ]
 },
 "panels": [
  {
   "title": "Pass Rate ($version)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "builds",
     "query": "select ( \"passed\" / ( \"total\" - \"skipped\" )) * 100 from (SELECT \"skipped_count\" AS \"skipped\", \"success_count\" AS \"passed\", \"tests\" AS \"total\" FROM \"builds\" WHERE $timeFilter  AND \"version\" =~ /^$version$/ )",
     "select": [
      [
       { "params": [ "skipped_count" ], "type": "field" },
       { "params": [ "skipped" ], "type": "alias" }
      ],
      [
       { "params": [ "success_count" ], "type": "field" },
       { "params": [ "passed" ], "type": "alias" }
      ],
      [
       { "params": [ "tests" ], "type": "field" },
       { "params": [ "total" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Platform/Failures",
   "type": "digrich-bubblechart-panel",
   "gridPos": { "h": 12, "w": 14, "x": 7, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_platform",
     "groupBy": [
      { "params": [ "platform" ], "type": "tag" }
     ],
     "measurement": "builds",
     "select": [
      [
       { "params": [ "failure_and_error_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Execution for All Platforms ($version)",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_result",
     "groupBy": [
      { "params": [ "result" ], "type": "tag" }
     ],
     "measurement": "tests",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "version", "operator": "=~", "value": "/^$version$/" },
      { "condition": "AND", "key": "result", "operator": "!=", "value": "skipped" }
     ]
    }
   ]
  },
  {
   "title": "Platform Failures",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_platform",
     "groupBy": [
      { "params": [ "platform" ], "type": "tag" }
     ],
     "measurement": "builds",
     "query": "SELECT \"failure_and_error_count\" AS \"Failures\" FROM \"builds\" WHERE (\"version\" =~ /^$version$/) AND $timeFilter GROUP BY \"platform\" ",
     "select": [
      [
       { "params": [ "failure_and_error_count" ], "type": "field" },
       { "params": [ "Failures" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    }
   ]
  },
  {
   "title": "Test Run Report ($version)",
   "type": "table",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 22 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "platform" ], "type": "tag" }
     ],
     "measurement": "builds",
     "query": "select \"platform\" as \"Platform\", \"Failed\", \"Passed\", \"Errored\", \"Total\", \"Skipped\", (\"Passed\" / (\"Total\" - \"Skipped\") ) * 100 as \"Pass Rate (%)\" FROM (SELECT \"failure_count\" AS \"Failed\", \"success_count\" AS \"Passed\", \"error_count\" AS \"Errored\", \"skipped_count\" AS \"Skipped\", \"tests\" AS \"Total\" FROM \"builds\" WHERE (\"version\" =~ /^$version$/) AND $timeFilter GROUP BY \"platform\")",
     "select": [
      [
       { "params": [ "failure_count" ], "type": "field" },
       { "params": [ "Failures" ], "type": "alias" }
      ],
      [
       { "params": [ "success_count" ], "type": "field" },
       { "params": [ "Success" ], "type": "alias" }
      ],
      [
       { "params": [ "error_count" ], "type": "field" },
       { "params": [ "Errors" ], "type": "alias" }
      ],
      [
       { "params": [ "skipped_count" ], "type": "field" },
       { "params": [ "Total" ], "type": "alias" }
      ],
      [
       { "params": [ "tests" ], "type": "field" },
       { "params": [ "Skipped" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "version", "operator": "=~", "value": "/^$version$/" }
     ]
    }
   ]
  },
  {
   "title": "Failed Tests ($version)",
   "type": "table",
   "gridPos": { "h": 10, "w": 21, "x": 0, "y": 32 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "result" ], "type": "tag" }
     ],
     "measurement": "tests",
     "query": "SELECT \"classname\", \"name\" FROM \"tests\" WHERE ( \"result\" = 'failure' OR \"result\" = 'error') AND \"version\" =~ /^$version$/ AND $timeFilter GROUP BY \"result\"",
     "select": [
      [
       { "params": [ "classname" ], "type": "field" }
      ],
      [
       { "params": [ "name" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "result", "operator": "=", "value": "failure" },
      { "condition": "OR", "key": "result", "operator": "=", "value": "error" },
      { "condition": "AND", "key": "platform", "operator": "=~", "value": "/^$platform$/" },
      { "condition": "AND", "key": "version", "operator": "=~", "value": "/^$Version$/" }
     ]
    }
   ]
  }
 ]
}